apiVersion: v1
kind: Service
metadata:
  name: tawazun
  labels:
    name: elhaam
    app: tawazun
  namespace: elhaam-tawazun
spec:
  type: NodePort
  ports:
  - name: tawazun-service
    port: 80
    targetPort: 80
    protocol: TCP
    type: LoadBalancer  
  selector:
    app: tawazun
    service: tawazun-svc