apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawazun-app
  labels:
    name: elhaam
    app: tawazun
    service: tawazun-svc
  namespace: elhaam-tawazun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun
  template:
    metadata:
      labels:
        service: tawazun-svc
        app: tawazun
    spec:
      containers:
      - image: abdullahkimrigh/tawazun-sda-hackathon:0.1
        name: tawazun-app
        ports:
        - containerPort: 8080
          name: tawazun
        livenessProbe:
          httpGet:
            path: /probes
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /probes
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /probes
            port: 80
          failureThreshold: 30
          periodSeconds: 10