apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawazun-app
  labels:
    name: elhaam
    service: tawazun-svc
    app: tawazun
  namespace: elhaam-tawazun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun
      service: tawazun-svc
  template:
    metadata:
      labels:
        app: tawazun
        service: tawazun-svc
    spec:
      containers:
        - image: elhaam/tawazun
          name: tawazun
          resources: 
            requests: 
              memory: 250Mi
              cpu: "250m"
            limits:
              memory: 512Mi
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tawazun-svc
  namespace: elhaam-tawazun
  labels: 
    name: elhaam
spec:
  selector:
    app: tawazun
    service: tawazun-svc
  ports:
    - port: 80 
      targetPort: 8080
  type: LoadBalancer  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
  namespace: elhaam-tawazun
  labels:
    app: sql
    name: elhaam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      volumes:
        - name: sql-pv-claim
          persistentVolumeClaim:
            claimName: sql-pv-claim
      containers:
        - image: mysql
          name: mysql
          resources: 
            requests: 
              memory: 250Mi
              cpu: "250m"
            limits:
              memory: 512Mi
              cpu: "500m"
          env:
            - name: MYSQL_USER
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "mysql"
            - name: MYSQL_PASSWORD
              value: "mysql"
            - name: MYSQL_ROOT_PASSWORD
              value: "mysql"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: sql-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
  namespace: elhaam-tawazun
  labels:
    type: local
    app: sql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pv-claim
  namespace: elhaam-tawazun
  labels:
    app: sql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  namespace: elhaam-tawazun
  labels:
    app: sql
    name: elhaam
spec:
  type: ClusterIP
  ports:
    - name: sql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: sql
