apiVersion: v1

kind: ResourceQuota

metadata:
  namespace: elhaam-tawazun

  name: elhaam-cpu-quota

spec:

  hard:

    requests.cpu: "2"

    requests.memory: 2Gi

    limits.cpu: "4"

    limits.memory: 4Gi
