apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs-db
  labels:
    name: elhaam
    type: cloud
  namespace: elhaam-tawazun
spec:
  storageClassName: mysql-db-ebs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-09ae750d97e198a16
    fsType: ext4